[package]
name = "dirus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
iced-x86 = "1.21.0"
msvc-demangler = "0.11.0"
object = "0.36.7"
pdb = "0.8.0"
